version: '1.0'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: feane
    env_file:
      - backend/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16-alpine
    container_name: postgres-test
    env_file:
      - .env
    ports:
      - 5433:5432