version: '1.0'

services:
  backend:
    image: node:18-alpine
    container_name: feane
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - backend/.env
    command: sh -c "cd backend && npm i -f && npm run start:dev"
    ports:
      - 3000:3000
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16-alpine
    container_name: postgres-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abrorbek
    ports:
      - 5433:5432